train:
  model_version : ResAttentionNetv1
  model_version_details : 原始版本
  load_pretrained_model : false
  pretrained_model_path : ''
  batch_size : 32
  num_workers : 4
  epoch : 100
  log_path : ./runs/
  learning_rate :
    base_learning_rate : 4.e-5
    step_size : 10
    gamma : 0.6
  best_model :
    loss : 10000  #替代符 在训练过程中发现小于它的会修改，训练结束后保存
    epoch : 0

dataset:
  img_size:
    range : 144
    doppler : 80
    angle : 64
  range_config :
    range_res : 0.41 #0.082*5
    range_max : 5.33 #0.082*5*13
  init_data_path : "/home/zhang_t/workspace/data/data_res"
  experiments_config_path : "/home/zhang_t/workspace/data/experiments_config.xls"
  save_path : "six_people"
  train_config :
    person : ['张螣','常远策','郭世纪','任梦琪','任楠','薛涵睿']
    place : ['宽阔走廊','大工位','狭窄走廊','狭窄走廊','茶水间','阳台']

        
